name = "Wezza MC"
author = "Wezza MC"
version = "26.1.2-r5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ac997ea4a90f3a19ad79fd11593c41242465a1a01b7e0312e6da608783db39f"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
