name = "Wezza MC"
author = "Wezza MC"
version = "26.1.2-r7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377b214ecb6ffd7c371e0baf79289b995d86f1d5d485be583ef496dc00437f18"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
